packages:
  - 'apps/*'
  - 'packages/components'
  - 'packages/error-handler'
  - 'packages/libs/*'
  - 'packages/middleware'
  - 'packages/utils/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  core-js: true
  esbuild: true
  nx: true
  postinstall-postinstall: true
  prisma: true
  sharp: true
  unrs-resolver: true
